name: GitHub Small Lab

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: yarn install

      - name: Show version info
        run: yarn run test

  build:
    runs-on: ubuntu-latest
    needs: run
    permissions:
      contents: read
      actions: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/tmnt150/B11223212-Lab-Pan
          flavor: |
            latest=false
          tags: |
            type=raw,value=dev
            type=sha,prefix=,suffix=,format=short

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max